### ISSUE TITLE
Not receiving Push Notifications if app not open

### ISSUE THREAD

**Issue by icerfish** [Jojocaster/do-you-app#5]
**Describe the bug**
Not receiving push notifications if the app is closed, potentially also if the app is just in the background 

**To Reproduce**
1. Install app
2. Open app
3. Close app (Potentially need to remove from background)
4. Wait for a show to start
5. Observe no notification
6. Open app once show has already started
7. Observe Notification as soon as app opens

**Expected behavior**
Notifications to be received as long as the App has been opened once before in the past no matter if app is in the background or completely closed, not just when the app is in the foreground

**Screenshots**
Will try record a video of behaviour tomorrow morning when there's a new show

**Smartphone (please complete the following information):**
 - Device: Samsung S22+
 - OS: Android 12

**Comment by Jojocaster** [comment]
Hey @icerfish , thanks for the feedback. Notifications are still in beta (and should have appeared as "Beta" in the current version, but it didn't make the cut) and will be improved soon. 

Currently, we're managing notifications locally - the app checks the live status, and tries to notify users when a new show is live. While this works (mostly / surprisingly) well on iOS,  Android tends to kill the process in the background and won't display anything until the app is resumed. 

The plan is to move to push notifications, which are more reliable than local notifications. I'll post an update here when implemented 😄

**Comment by icerfish** [comment]
It should be possible on Android via a similar approach to using an alarm clock, but my assumption is that you would need to implement it natively using a BroadcastReceiver and the AlarmManager Service, but admittedly would be a little overkill compared to an implementation using Firebase Remote Messaging

But either way great work, if you ever need any help let me know! Have done Android for years, and React Native here and there so happy to help where I can :)

**Comment by Jojocaster** [comment]
@icerfish closing, all notifications should work just fine now 🎉
